### ISSUE TITLE
希望能公开《Region-Focused Network for Dense Captioning》的代码

### ISSUE THREAD

**Issue by bigbrother001** [VILAN-Lab/EGSS#5]
[Region-Focused Network for Dense Captioning](https://github.com/VILAN-Lab/DesCap)无法访问了，希望能分享这篇文章的代码

**Comment by VILAN-Lab** [comment]
非常感谢您对我们工作的关注。DesCap的主要代码已开源。
[DesCap](https://github.com/VILAN-Lab/DesCap)
